-- Auto-generated by tools/build-release.ps1
-- Do not edit manually.
local __modules = {}
local __cache = {}

__modules["core.dependencies"] = function(__require)
local function loadFromUrl(url)
return loadstring(game:HttpGet(url))()
end

local Dependencies={
Fluent=loadFromUrl("https://github.com/dawid-scripts/Fluent/releases/latest/download/main.lua"),
SaveManager=loadFromUrl("https://raw.githubusercontent.com/dawid-scripts/Fluent/master/Addons/SaveManager.lua"),
InterfaceManager=loadFromUrl("https://raw.githubusercontent.com/dawid-scripts/Fluent/master/Addons/InterfaceManager.lua"),
}

return Dependencies
end

__modules["core.window"] = function(__require)
local WindowFactory={}

function WindowFactory.create(Fluent)
local window=Fluent:CreateWindow({
Title="MahmutHub "..Fluent.Version,
SubTitle="by Mahmut",
TabWidth=160,
Size=UDim2.fromOffset(580,460),
Acrylic=true,
Theme="Dark",
MinimizeKey=Enum.KeyCode.LeftControl,
})

local tabs={
Main=window:AddTab({Title="Main",Icon=""}),
Settings=window:AddTab({Title="Settings",Icon="settings"}),
}

return window,tabs
end

return WindowFactory
end

__modules["init"] = function(__require)
local Dependencies=require(script.core.dependencies)
local WindowFactory=require(script.core.window)
local MainTab=require(script.tabs.main)
local SettingsTab=require(script.tabs.settings)

local Fluent=Dependencies.Fluent
local SaveManager=Dependencies.SaveManager
local InterfaceManager=Dependencies.InterfaceManager

local Window,Tabs=WindowFactory.create(Fluent)
local Options=Fluent.Options

local context={
Fluent=Fluent,
SaveManager=SaveManager,
InterfaceManager=InterfaceManager,
Window=Window,
Tabs=Tabs,
Options=Options,
}

MainTab.build(context)
SettingsTab.build(context)

Window:SelectTab(1)

Fluent:Notify({
Title="Fluent",
Content="The script has been loaded.",
Duration=8,
})

SaveManager:LoadAutoloadConfig()
end

__modules["modules.main_tab"] = function(__require)
local MainTab={}

function MainTab.build(context)
local Fluent=context.Fluent
local Window=context.Window
local Tabs=context.Tabs
local Options=context.Options

Fluent:Notify({
Title="Notification",
Content="This is a notification",
SubContent="SubContent",
Duration=5,
})

Tabs.Main:AddParagraph({
Title="Paragraph",
Content="This is a paragraph.\nSecond line!",
})

Tabs.Main:AddButton({
Title="Button",
Description="Very important button",
Callback=function()
Window:Dialog({
Title="Title",
Content="This is a dialog",
Buttons={
{
Title="Confirm",
Callback=function()
print("Confirmed the dialog.")
end,
},
{
Title="Cancel",
Callback=function()
print("Cancelled the dialog.")
end,
},
},
})
end,
})

local Toggle=Tabs.Main:AddToggle("MyToggle",{Title="Toggle",Default=false})
Toggle:OnChanged(function()
print("Toggle changed:",Options.MyToggle.Value)
end)
Options.MyToggle:SetValue(false)

local Slider=Tabs.Main:AddSlider("Slider",{
Title="Slider",
Description="This is a slider",
Default=2,
Min=0,
Max=5,
Rounding=1,
Callback=function(Value)
print("Slider was changed:",Value)
end,
})

Slider:OnChanged(function(Value)
print("Slider changed:",Value)
end)

Slider:SetValue(3)

local Dropdown=Tabs.Main:AddDropdown("Dropdown",{
Title="Dropdown",
Values={"one","two","three","four","five","six","seven","eight","nine","ten","eleven","twelve","thirteen","fourteen"},
Multi=false,
Default=1,
})

Dropdown:SetValue("four")
Dropdown:OnChanged(function(Value)
print("Dropdown changed:",Value)
end)

local MultiDropdown=Tabs.Main:AddDropdown("MultiDropdown",{
Title="Dropdown",
Description="You can select multiple values.",
Values={"one","two","three","four","five","six","seven","eight","nine","ten","eleven","twelve","thirteen","fourteen"},
Multi=true,
Default={"seven","twelve"},
})

MultiDropdown:SetValue({
three=true,
five=true,
seven=false,
})

MultiDropdown:OnChanged(function(Value)
local Values={}
for Value,State in next,Value do
table.insert(Values,Value)
end
print("Mutlidropdown changed:",table.concat(Values,", "))
end)

local Colorpicker=Tabs.Main:AddColorpicker("Colorpicker",{
Title="Colorpicker",
Default=Color3.fromRGB(96,205,255),
})

Colorpicker:OnChanged(function()
print("Colorpicker changed:",Colorpicker.Value)
end)

Colorpicker:SetValueRGB(Color3.fromRGB(0,255,140))

local TColorpicker=Tabs.Main:AddColorpicker("TransparencyColorpicker",{
Title="Colorpicker",
Description="but you can change the transparency.",
Transparency=0,
Default=Color3.fromRGB(96,205,255),
})

TColorpicker:OnChanged(function()
print("TColorpicker changed:",TColorpicker.Value,"Transparency:",TColorpicker.Transparency)
end)

local Keybind=Tabs.Main:AddKeybind("Keybind",{
Title="KeyBind",
Mode="Toggle",
Default="LeftControl",
Callback=function(Value)
print("Keybind clicked!",Value)
end,
ChangedCallback=function(New)
print("Keybind changed!",New)
end,
})

Keybind:OnClick(function()
print("Keybind clicked:",Keybind:GetState())
end)

Keybind:OnChanged(function()
print("Keybind changed:",Keybind.Value)
end)

task.spawn(function()
while true do
task.wait(1)

local state=Keybind:GetState()
if state then
print("Keybind is being held down")
end

if Fluent.Unloaded then
break
end
end
end)

Keybind:SetValue("MB2","Toggle")

local Input=Tabs.Main:AddInput("Input",{
Title="Input",
Default="Default",
Placeholder="Placeholder",
Numeric=false,
Finished=false,
Callback=function(Value)
print("Input changed:",Value)
end,
})

Input:OnChanged(function()
print("Input updated:",Input.Value)
end)
end

return MainTab
end

__modules["modules.settings_tab"] = function(__require)
local SettingsTab={}

function SettingsTab.build(context)
local SaveManager=context.SaveManager
local InterfaceManager=context.InterfaceManager
local Fluent=context.Fluent
local Tabs=context.Tabs

SaveManager:SetLibrary(Fluent)
InterfaceManager:SetLibrary(Fluent)

SaveManager:IgnoreThemeSettings()
SaveManager:SetIgnoreIndexes({})

InterfaceManager:SetFolder("FluentScriptHub")
SaveManager:SetFolder("FluentScriptHub/specific-game")

InterfaceManager:BuildInterfaceSection(Tabs.Settings)
SaveManager:BuildConfigSection(Tabs.Settings)
end

return SettingsTab
end

__modules["tabs.main"] = function(__require)
local MainTab={}

function MainTab.build(context)
local Fluent=context.Fluent
local Window=context.Window
local Tabs=context.Tabs
local Options=context.Options

Fluent:Notify({
Title="Notification",
Content="This is a notification",
SubContent="SubContent",
Duration=5,
})

Tabs.Main:AddParagraph({
Title="Paragraph",
Content="This is a paragraph.\nSecond line!",
})

Tabs.Main:AddButton({
Title="Button",
Description="Very important button",
Callback=function()
Window:Dialog({
Title="Title",
Content="This is a dialog",
Buttons={
{
Title="Confirm",
Callback=function()
print("Confirmed the dialog.")
end,
},
{
Title="Cancel",
Callback=function()
print("Cancelled the dialog.")
end,
},
},
})
end,
})

local Toggle=Tabs.Main:AddToggle("MyToggle",{Title="Toggle",Default=false})
Toggle:OnChanged(function()
print("Toggle changed:",Options.MyToggle.Value)
end)
Options.MyToggle:SetValue(false)

local Slider=Tabs.Main:AddSlider("Slider",{
Title="Slider",
Description="This is a slider",
Default=2,
Min=0,
Max=5,
Rounding=1,
Callback=function(Value)
print("Slider was changed:",Value)
end,
})

Slider:OnChanged(function(Value)
print("Slider changed:",Value)
end)

Slider:SetValue(3)

local Dropdown=Tabs.Main:AddDropdown("Dropdown",{
Title="Dropdown",
Values={"one","two","three","four","five","six","seven","eight","nine","ten","eleven","twelve","thirteen","fourteen"},
Multi=false,
Default=1,
})

Dropdown:SetValue("four")
Dropdown:OnChanged(function(Value)
print("Dropdown changed:",Value)
end)

local MultiDropdown=Tabs.Main:AddDropdown("MultiDropdown",{
Title="Dropdown",
Description="You can select multiple values.",
Values={"one","two","three","four","five","six","seven","eight","nine","ten","eleven","twelve","thirteen","fourteen"},
Multi=true,
Default={"seven","twelve"},
})

MultiDropdown:SetValue({
three=true,
five=true,
seven=false,
})

MultiDropdown:OnChanged(function(Value)
local Values={}
for Value,State in next,Value do
table.insert(Values,Value)
end
print("Mutlidropdown changed:",table.concat(Values,", "))
end)

local Colorpicker=Tabs.Main:AddColorpicker("Colorpicker",{
Title="Colorpicker",
Default=Color3.fromRGB(96,205,255),
})

Colorpicker:OnChanged(function()
print("Colorpicker changed:",Colorpicker.Value)
end)

Colorpicker:SetValueRGB(Color3.fromRGB(0,255,140))

local TColorpicker=Tabs.Main:AddColorpicker("TransparencyColorpicker",{
Title="Colorpicker",
Description="but you can change the transparency.",
Transparency=0,
Default=Color3.fromRGB(96,205,255),
})

TColorpicker:OnChanged(function()
print("TColorpicker changed:",TColorpicker.Value,"Transparency:",TColorpicker.Transparency)
end)

local Keybind=Tabs.Main:AddKeybind("Keybind",{
Title="KeyBind",
Mode="Toggle",
Default="LeftControl",
Callback=function(Value)
print("Keybind clicked!",Value)
end,
ChangedCallback=function(New)
print("Keybind changed!",New)
end,
})

Keybind:OnClick(function()
print("Keybind clicked:",Keybind:GetState())
end)

Keybind:OnChanged(function()
print("Keybind changed:",Keybind.Value)
end)

task.spawn(function()
while true do
task.wait(1)

local state=Keybind:GetState()
if state then
print("Keybind is being held down")
end

if Fluent.Unloaded then
break
end
end
end)

Keybind:SetValue("MB2","Toggle")

local Input=Tabs.Main:AddInput("Input",{
Title="Input",
Default="Default",
Placeholder="Placeholder",
Numeric=false,
Finished=false,
Callback=function(Value)
print("Input changed:",Value)
end,
})

Input:OnChanged(function()
print("Input updated:",Input.Value)
end)
end

return MainTab
end

__modules["tabs.settings"] = function(__require)
local SettingsTab={}

function SettingsTab.build(context)
local SaveManager=context.SaveManager
local InterfaceManager=context.InterfaceManager
local Fluent=context.Fluent
local Tabs=context.Tabs

SaveManager:SetLibrary(Fluent)
InterfaceManager:SetLibrary(Fluent)

SaveManager:IgnoreThemeSettings()
SaveManager:SetIgnoreIndexes({})

InterfaceManager:SetFolder("FluentScriptHub")
SaveManager:SetFolder("FluentScriptHub/specific-game")

InterfaceManager:BuildInterfaceSection(Tabs.Settings)
SaveManager:BuildConfigSection(Tabs.Settings)
end

return SettingsTab
end

local function __require(moduleName)
    if __cache[moduleName] ~= nil then
        return __cache[moduleName]
    end

    local moduleLoader = __modules[moduleName]
    if not moduleLoader then
        error("Module not found: " .. tostring(moduleName), 2)
    end

    local result = moduleLoader(__require)
    __cache[moduleName] = result
    return result
end

__require("init")

