param(
    [string]$BuildPath = "build",
    [string]$OutputPath = "release/mahmut-hub.lua"
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path $BuildPath)) {
    throw "Build folder '$BuildPath' not found. Run 'darklua process --config .darklua.json src build' first."
}

$buildRoot = (Resolve-Path $BuildPath).Path
$outputDir = Split-Path -Parent $OutputPath
if ($outputDir -and -not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir | Out-Null
}

$luaFiles = Get-ChildItem -Path $buildRoot -Recurse -File -Filter "*.lua" | Sort-Object FullName
if (-not $luaFiles) {
    throw "No Lua files found in '$BuildPath'."
}

$builder = New-Object System.Text.StringBuilder

[void]$builder.AppendLine("-- Auto-generated by tools/build-release.ps1")
[void]$builder.AppendLine("-- Do not edit manually.")
[void]$builder.AppendLine("local __modules = {}")
[void]$builder.AppendLine("local __cache = {}")

foreach ($file in $luaFiles) {
    $relative = $file.FullName.Substring($buildRoot.Length).TrimStart('\').Replace('\', '/')
    $moduleId = ($relative -replace '\.lua$', '').Replace('/', '.')
    $content = Get-Content -Path $file.FullName -Raw
    $content = [regex]::Replace($content, 'require\\(script\\.([A-Za-z0-9_\\.]+)\\)', '__require("$1")')

    [void]$builder.AppendLine("")
    [void]$builder.AppendLine(('__modules["{0}"] = function(__require)' -f $moduleId))
    [void]$builder.AppendLine($content.TrimEnd())
    [void]$builder.AppendLine("end")
}

[void]$builder.AppendLine("")
[void]$builder.AppendLine("local function __require(moduleName)")
[void]$builder.AppendLine("    if __cache[moduleName] ~= nil then")
[void]$builder.AppendLine("        return __cache[moduleName]")
[void]$builder.AppendLine("    end")
[void]$builder.AppendLine("")
[void]$builder.AppendLine("    local moduleLoader = __modules[moduleName]")
[void]$builder.AppendLine("    if not moduleLoader then")
[void]$builder.AppendLine('        error("Module not found: " .. tostring(moduleName), 2)')
[void]$builder.AppendLine("    end")
[void]$builder.AppendLine("")
[void]$builder.AppendLine("    local result = moduleLoader(__require)")
[void]$builder.AppendLine("    __cache[moduleName] = result")
[void]$builder.AppendLine("    return result")
[void]$builder.AppendLine("end")
[void]$builder.AppendLine("")
[void]$builder.AppendLine('__require("init")')

Set-Content -Path $OutputPath -Value $builder.ToString() -Encoding utf8
Write-Host "Release file generated at $OutputPath"
